name: Mcdksr

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 99999999

    steps:
    - name: Nssm Ve NGROK iNİYOR
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/hayday1/gettovds/main/Files/nssm.exe -OutFile nssm.exe
    - name: Nssm Ve Ngrok Kopyalanıyorr
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Ngrok Hesabınıza  Doğrulanıyorrr
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Önemli Gibi Duran Dosyalar İNiyorr çuf çuf
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/hayday1/gettovds/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/mcdksrs/McdVds/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hayday1/gettovds/main/Files/loop.bat -OutFile loop.bat
    - name: Ngrok nE kOMİK AdAmsın bE
      run: start NGROK-US.bat
    - name: şşşt sessiz Rdp`ye erişiyoruz
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Tünele Girdik Korkmayın
      run: sc start ngrok
    - name: Bağlan Hadi
      run: cmd /c NGROK-CHECK.bat
    - name: Hepsi Tamam Patron.
      run: cmd /c loop.bat 
      
